name = "MakieWebinar"
uuid = "0c910606-8410-48ea-b5e6-b6a751ad3471"
authors = [" <>"]
version = "0.1.0"

[deps]
BlockComponents = "1ef5d832-be8e-447f-9f2c-8b5d17d15fd3"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
DyadControlSystems = "6f9e59d0-2838-4fee-9bce-c163a6c9592b"
DyadEcosystemDependencies = "7bc808db-8006-421e-b546-062440d520b7"
DyadExampleComponents = "2fe18900-c5b3-5d06-b340-7a6acf678e36"
DyadInterface = "99806f68-afab-45ca-9d8c-ceff6bc61f54"
ElectricalComponents = "3fc4c519-469d-4ff5-98c9-d4d06b1514a2"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
ModelingToolkitInputs = "9c47c465-b61a-4984-aca2-8d7e8f154266"
Moshi = "2e0e35c7-a2e4-4343-998d-7ef72827ed2d"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
OrdinaryDiffEqDefault = "50262376-6c5a-4cf5-baba-aaf4f84d72d7"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
RotationalComponents = "824fa3ed-d7dc-4365-8bdf-ac77a1ac2011"
RuntimeGeneratedFunctions = "7e49a35a-f44a-4d26-94aa-eba1b4ca6b47"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SymbolicIndexingInterface = "2efcf032-c050-4f8e-a9bb-153293bab1f5"
ThermalComponents = "084a29d9-4f48-4925-95b4-b7d4c79725f4"
TranslationalComponents = "42acc370-819b-4877-bdd6-eb3294461f5d"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[compat]
BlockComponents = "3.0.4"
CairoMakie = "0.15.8"
Colors = "0.13.1"
Downloads = "1.6.0"
DyadControlSystems = "1.7.5"
DyadEcosystemDependencies = "=0.10.6"
DyadExampleComponents = "1.1.4"
ElectricalComponents = "1.1.4"
GLMakie = "0.13.8"
GeometryBasics = "0.5.10"
Makie = "0.24.8"
Markdown = "1"
ModelingToolkitInputs = "0.2.0"
Observables = "0.5.5"
RotationalComponents = "1.2.0"
SciMLBase = "2.128.0"
SymbolicIndexingInterface = "0.3.46"
ThermalComponents = "1.0.3"
TranslationalComponents = "1.1.4"
WGLMakie = "0.13.8"

[dyad]
kernel = "2.0.0"

[extras]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["CSV", "DataFrames", "Plots", "Test"]
