[deps]
DyadInterface = "99806f68-afab-45ca-9d8c-ceff6bc61f54"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
TurkeyDemo = "03da8933-3897-4a09-a9ba-0cf9ce1f70ee"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[sources]
TurkeyDemo = {path = ".."}
