name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

env:
  JULIA_PKG_SERVER: internal.juliahub.com

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}

    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        version:
          - "1.10"
          - "1.11"
        os:
          - self-hosted
        arch:
          - x64

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: julia-actions/setup-julia@5c9647d97b78a5debe5164e9eec09d653d29bd71 # v2.6.1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - name: "Set up private JuliaHub registries"
        uses: "JuliaComputing/set-up-private-juliahub-registries@93a57d352d8435399461ffe68df41d193e4619b3" # v1.3.0
        with:
          encoded-juliahub-token: "${{ secrets.JULIAHUB_TOKEN_ENCODED }}"
          enable-JuliaHubRegistry: "true"
          # ssh-key: "${{ secrets.JULIASIM_REGISTRY_SSH_KEY }}"

      - name: "Instantiate CI environment"
        run: julia --project=.ci -e 'using Pkg; Pkg.instantiate()'

      - name: "Run CI script"
        run: julia --project=.ci .ci/run.jl
